### ISSUE TITLE
[DataCap Application] AWS-ENCODE

### ISSUE THREAD

**Issue by alyssa32M** [luhong123/QC-Data-center#11]
### Data Owner Name

NHGRI

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.encodeproject.org/

### Social Media Handle

Alyssa

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

1.32PiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f17h6wblshweb7uj4ijxkdroqsdjcl7qijjzi6n3i

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Project-The ENCODE Consortium not only produces high-quality data, but also analyzes the data in an integrative fashion. The ENCODE Encyclopedia organizes the most salient analysis products into annotations and provides tools to search and visualize them.
organization-We are a web3 organization named dataup. We help data owner to store data.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
ENCODE investigators employ a variety of assays and methods to identify functional elements. The discovery and annotation of gene elements is accomplished primarily by sequencing a diverse range of RNA sources, comparative genomics, integrative bioinformatic methods, and human curation. Regulatory elements are typically investigated through DNA hypersensitivity assays, assays of DNA methylation, and immunoprecipitation (IP) of proteins that interact with DNA and RNA, i.e., modified histones, transcription factors, chromatin regulators, and RNA-binding proteins, followed by sequencing.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We use Lotus to prepare data. We transfer car files to SPs.
```

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://encode-public/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03100009 Hong Kong
f01084941 Hong Kong
f03100002 Shenzhen
f03100000 Shenzhen
f01975299 Shenzhen
f01084413 Changsha
f03161261 New York
f03192503 Hong Kong
f03189917 Dulles
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by alyssa32M** [comment]
@luhong123 Dear allocator, this is my application. Please give us feedback. Thank you.

**Comment by luhong123** [comment]
Please read the contents of https://github.com/filecoin-project/notary-governance/issues/1071#issuecomment-1902740577 for details on the rule, thank you!

**Comment by luhong123** [comment]
If you don't need any help,Please pay a total of `101 FIL` to `f1apw6of55wzdbpjpnnyenv56ensi4iisaxgmigzi` for information verification (1 FIL)  and data pledge fees (100 FIL).

**Comment by luhong123** [comment]
1. Are you uploading this open data on behalf of an individual or a company?
2. Are the data as well as the SP sealed ready?
3. Do all SPs support retrieval or spark retrieval？

**Comment by alyssa32M** [comment]
@luhong123 Dear allocator, we've read all contents you provided to me, thank you.

We've paid Fil to your account, please check it.

We are a web3 organization and I'm the op of our organization.
Yes, we have stored this dataset in our servers. The sps in our application are ready for our deals. If we have more sps to cooperation, we will provide the update to you.
Yes, we provided spark retrieval rules to sps and they have updated their code. We will keep focusing on their ability of retrieval.

**Comment by luhong123** [comment]
f01843994 US

Please provide proof of the geographic location of the SPs to [m4a1i233@gmail.com](mailto:m4a1i233@gmail.com)

**Comment by alyssa32M** [comment]
@luhong123 OK. I have sent it.

**Comment by luhong123** [comment]
confirmed

**Comment by luhong123** [comment]
checker:manualTrigger

**Comment by luhong123** [comment]
Nice retrieval rate.
![image](https://github.com/user-attachments/assets/4a5819c1-3d20-4e95-98ea-85d2a9e19f32)

But it doesn't match what was first disclosed, so please confirm the SP you're working with and rework it!
![image](https://github.com/user-attachments/assets/605f15cd-9e7b-4019-bf6e-cdf79ee564d6)

**Comment by luhong123** [comment]
checker:manualTrigger

**Comment by luhong123** [comment]
Got it

**Comment by luhong123** [comment]
Good retrieval rate, would like to see more SPs join in the next round with early disclosure

**Comment by luhong123** [comment]
checker:manualTrigger

**Comment by alyssa32M** [comment]
@luhong123 Dear allocator, we provide several sps to our work.
f03100002 SZ
f01975299 China
f03192503 HongKong
f01084413 China
f01084941 HongKong

**Comment by alyssa32M** [comment]
checker:manualTrigger

**Comment by luhong123** [comment]
checker:manualTrigger

**Comment by alyssa32M** [comment]
@luhong123 Dear allocator, I noticed that the retrieval results for the new sps added to the list are not very good at the moment. I've already communicated with sps, and they promise to show better results in the next cid report. Also, I've got experience with previous sp's that I've worked with to share with new ones. Better results will be shown in subsequent reports.

**Comment by luhong123** [comment]
Got it

> @luhong123 Dear allocator, I noticed that the retrieval results for the new sps added to the list are not very good at the moment. I've already communicated with sps, and they promise to show better results in the next cid report. Also, I've got experience with previous sp's that I've worked with to share with new ones. Better results will be shown in subsequent reports.

**Comment by luhong123** [comment]
> Number of replicas to store
> 4

The current number of copies is 8. Please confirm.

**Comment by luhong123** [comment]
> 2 storage providers sealed too much duplicate data - [f03161261](https://filfox.info/en/address/f03161261): 49.88%, [f03189917](https://filfox.info/en/address/f03189917): 49.89%

Same bug.
https://github.com/fidlabs/allocator-tooling/issues/73

**Comment by luhong123** [comment]
![image](https://github.com/user-attachments/assets/5dcc9854-6266-4c35-adcd-9af3825261af)
Two retrievals are good so far, will be watching for changes in retrieval rates and hope to see good retrievals before the next round is triggered

**Comment by luhong123** [comment]
checker:manualTrigger

**Comment by luhong123** [comment]
Multiple occurrences of undisclosed SPs, although the retrieval rate is good, it violates the relevant rules, please give a reasonable explanation, or else consider suspending the distribution of datacap

**Comment by alyssa32M** [comment]
@luhong123 Dear allocator, that is because sps have some different plan that delayed our process, we've just have to find new sps to work.
